version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: user
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:4.2.16-bionic
    environment:
      MONGO_INITDB_DATABASE: logs
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

  broker-services:
    build:
      context: ../broker-service
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8080:80"
    deploy:
      mode: replicated
      replicas: 1

  auth-service:
    build:
      context: ../authentication-service
      dockerfile: ./Dockerfile
    environment:
      dbEngine: postgres
      dbUser: admin
      dbPassword: password
      dbName: user
      dbHost: postgres
      dbPort: 5432
      dbSSLMode: disable
    deploy:
      mode: replicated
      replicas: 1

  logger-service:
    build:
      context: ../logger-service
      dockerfile: ./Dockerfile
    deploy:
      mode: replicated
      replicas: 1

volumes:
  postgres-data:
  mongodb-data:


